/System/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/lpsdesk/PycharmProjects/PBcore_m/PBCore/scripts/pbcore_csv.py -g
Loading graphical user interface
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/lpsdesk/PycharmProjects/PBcore_m/PBCore/scripts/pbcore_csv.py", line 1920, in run
    new_xml = minidom.parseString(self.generate_pbcore(record, files))
  File "/Users/lpsdesk/PycharmProjects/PBcore_m/PBCore/scripts/pbcore_csv.py", line 1333, in generate_pbcore
    pres_master = self._build_preservation_master(record, preservation_file_set)
  File "/Users/lpsdesk/PycharmProjects/PBcore_m/PBCore/scripts/pbcore_csv.py", line 789, in _build_preservation_master
    new_mast_part = InstantiationPart(location=self.settings.get('PBCOREINSTANTIATION','InstantiationIdentifierSource'), duration=f.totalRunningTimeSMPTE)
  File "/Library/Python/2.7/site-packages/onesheet/TimeBasedMetadata.py", line 56, in totalRunningTimeSMPTE
    return results.group(0)
AttributeError: 'NoneType' object has no attribute 'group'

